### ISSUE TITLE
Dependency on unsupported filesize gem

### ISSUE THREAD

**Issue by petergoldstein** [pawurb/ruby-pg-extras#12]
The gem has a dependency on the now unsupported `filesize` gem -  https://github.com/dominikh/filesize

The dependency is extremely minor.  It consists of two references

1. Conversion of `1 MB` to a constant int value, which can just be replaced by the constant int value 
2. Checking whether an index size is above a minimum, and hence should be analyzed in the `unused_indexes` case

Given that the dependency is now unsupported, it should probably be removed.  I'm happy to put together a PR if there is interest in resolving the issue.

**Comment by pawurb** [comment]
Would be great, thank you!
