### ISSUE TITLE
Incorporating pg_stat_monitor support?

### ISSUE THREAD

**Issue by skatkov** [pawurb/ruby-pg-extras#21]
I was wondering, if there are any plans or ideas to use pg_stat_monitor extension in this gem? Just from my rough research, it seems that a lot of data point seems similar, but there are quite a lot of useful datapoints on top.

More info could be found here:
https://www.percona.com/blog/understand-your-postgresql-workloads-better-with-pg_stat_monitor/

**Comment by pawurb** [comment]
Currently I don't have such plans, but I'm always open to PRs.
