### ISSUE TITLE
auto_explain feature support

### ISSUE THREAD

**Issue by skatkov** [pawurb/ruby-pg-extras#22]
Sorry that I'm creating another issue. 

I'd like to use auto_explain feature on our production instance. But it doesn't seem that this gem comes  with any support for it.

Maybe I'm missing something? Would you be keen to add support for that as well?

Thanks for a great gem

**Comment by pawurb** [comment]
Hi. auto_explain is a mechanism for appending more info to pg logs, I don't know how it should work with this gem. You can manually run explain on all the reported bottleneck queries. I'll close this one for now, please open a PR if you'll have any idea on how to integrate it.
