### ISSUE TITLE
support tables as strings instead of putsing

### ISSUE THREAD

**Issue by matti** [pawurb/ruby-pg-extras#9]
Thanks for this awesome gem - I made a quick monkey patch to puts to return strings so that the output can be caputered/displayed differently. I think this is valid usecase to implement properly in the gem.

```
RubyPGExtras.puts_returns_string = true
# now all table prints return uncolorized strings
```

```
module RubyPGExtras
  @@puts_returns_string = false

  def self.puts_returns_string
    @@puts_returns_string
  end

  def self.puts_returns_string=(value)
    @@puts_returns_string = value
  end
end

class String
  REGEXP_PATTERN = /\033\[([0-9]+);([0-9]+);([0-9]+)m(.+?)\033\[0m|([^\033]+)/m

  def uncolorize
    self.scan(REGEXP_PATTERN).inject("") do |str, match|
      str << (match[3] || match[4])
    end
  end
end

module RubyPGExtras
  def self.puts(args)
    if @@puts_returns_string
      args.to_s.uncolorize
    else
      Kernel.puts args
    end
  end
end

module RubyPGExtras
  class DiagnosePrint
    def puts(args)
      RubyPGExtras.puts args
    end
  end
end

module RubyPGExtras
  class TableInfoPrint
    def puts(args)
      RubyPGExtras.puts args
    end
  end
end

module RubyPGExtras
  class IndexInfoPrint
    def puts(args)
      RubyPGExtras.puts args
    end
  end
end
```

**Comment by pawurb** [comment]
Also, in addition to disabling colors with an ENV variable you could add a new `in_format` option e.g. `ascii`.

**Comment by matti** [comment]
I just want the table output as strings to be stored in files etc and not to spend time parsing json etc.

and my monkeypatch is not proposed implementation, just something I did fast.

**Comment by matti** [comment]
and another usecase is to for example have a sinatra etc route like

get "/table_info" do
  PgExtras.table_info
end

again, much easier to output text instead of json+parse

**Comment by matti** [comment]
and, my monkeypatch is "that complex" because the pgextras code doesnt already have that ":ascii" format which would then be used by :table.

**Comment by matti** [comment]
like, instead, :table is formatting+puts in a one go, then it could be composer of :ascii+puts

anyway, just saying that pgextras could be refactored. I'm already good with my monkeypatch.

**Comment by pawurb** [comment]
Ok. I don't really see an urgent need for this feature, so if you don't feel like implementing it I'll close the issues for now.
